### ISSUE TITLE
Solarportal encrypted connection?

### ISSUE THREAD

**Issue by GoSpursGoNL** [cyberjunky/home-assistant-custom-components#10]
Thanks for the SolarPortal component, I like it. Since 6 months or so, the [Omnik portal website](https://www.omnikportal.com/) switched to https. I would like to ask you if you could check whether it is now also possible to talk to their API securely, and if possible update the component.

This way the username and password would no longer be sent unencrypted. Thanks in advance!

**Comment by cyberjunky** [comment]
I tried to simply insert https, but get these errors
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:841)

Need more time.

**Comment by cyberjunky** [comment]
Cannot find a working implementation, so I close it.
I cannot reverse engineer it.
When a library pops up I will investigate again on how to port it.
