### ISSUE TITLE
Toon climate 

### ISSUE THREAD

**Issue by Sparky32** [cyberjunky/home-assistant-custom-components#17]
Hi . Thx for the great work 
Any id how to get the ui card back in  Lovelace . I lost the option home/sleep/away/comfort

**Comment by Hans110** [comment]
> Hi . Thx for the great work
> Any id how to get the ui card back in Lovelace . I lost the option home/sleep/away/comfort

I got it back in the following way:
1. Press top right corner and "Configure UI"
2. Press + bottom right corner and "Add entities"
3. Give it the title you want and select entity "climate.toon_thermostat"

**Comment by Sparky32** [comment]
Bedankt Hans . Mijn vrouwtje is weer helemaal blij
