### ISSUE TITLE
Toon not working in version 0.88

### ISSUE THREAD

**Issue by zuidwijk** [cyberjunky/home-assistant-custom-components#19]
Updated from 0.87.0 to 0.88.0 and now Toon isn't working anymore:

```
2019-02-21 17:10:53 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform toon
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/toon/climate.py", line 21, in setup_platform
    add_entities([ThermostatDevice(hass)], True)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/toon/climate.py", line 31, in __init__
    self.thermos = hass.data[toon_main.TOON_HANDLE]
KeyError: 'toon_handle'
```

**Comment by Jeltel** [comment]
Same here :(

**Comment by RudolfRendier** [comment]
It seems to be loading the default component in 'components/toon/' and is complaining about its toon_handle:

https://github.com/home-assistant/home-assistant/blob/127c55e0c196dc6ffd321c1ad28b533f636faf79/homeassistant/components/toon/__init__.py#L25

https://github.com/home-assistant/home-assistant/blob/127c55e0c196dc6ffd321c1ad28b533f636faf79/homeassistant/components/toon/climate.py#L31

Maybe a name conflict resulting in loading the incorrect component?

About 20 days ago the structure for the original component changed:
https://github.com/home-assistant/home-assistant/commit/e2d3c27e8515d6bce546382a79c717891bcb5905#diff-91fb2a3ec4c7c63a413b56d3239c3da6

**Comment by cyberjunky** [comment]
Can you create directory custom_components/toon/ and move custom_components/climate/toon.py into it and rename it to climate.py
That seems to work here.

**Comment by Jeltel** [comment]
@cyberjunky That works.

Strange, because for the boilerstatus component the exact suggestion was given in the log. But not for the climate component.

**Comment by cyberjunky** [comment]
I think it's a bug in home assistant.
I need to update all custom_components readme's

**Comment by zuidwijk** [comment]
I'll try it out tonight :+1:

**Comment by joostvanmourik** [comment]
> Can you create directory custom_components/toon/ and move custom_components/climate/toon.py into it and rename it to climate.py
> That seems to work here.

That seems to do the trick. Thanx (also does the trick with the Google Assistant enabled version)

**Comment by rickvnl** [comment]
> > Can you create directory custom_components/toon/ and move custom_components/climate/toon.py into it and rename it to climate.py
> > That seems to work here.
> 
> That seems to do the trick. Thanx (also does the trick with the Google Assistant enabled version)

Hi, what version are you talking about? I'm asking because I can't control my rooted Toon with GA.

**Comment by cyberjunky** [comment]
@rickvnl in the Google Assistant issue I posted a sort of working version
https://github.com/cyberjunky/home-assistant-custom-components/files/2683932/toon.zip

It has issues setting manual temp, and getting back to modes I understood, it needs some work.

**Comment by zuidwijk** [comment]
> Can you create directory custom_components/toon/ and move custom_components/climate/toon.py into it and rename it to climate.py
> That seems to work here.

Confirmed, it worked for me too!

**Comment by rudyo85** [comment]
> Can you create directory custom_components/toon/ and move custom_components/climate/toon.py into it and rename it to climate.py
> That seems to work here.

Worked for me too. Thx!
