### ISSUE TITLE
Home Assistant 0.89.0 breaks component

### ISSUE THREAD

**Issue by lxz81** [cyberjunky/home-assistant-custom-components#20]
I am not familiar with checking out/in, but to get the component working in HASS 0.89.0, I had to change/add something in the climate.py file.

I changed the imports to the following:
```
from homeassistant.components.climate import (ClimateDevice, PLATFORM_SCHEMA)
from homeassistant.components.climate.const import (SUPPORT_TARGET_TEMPERATURE, SUPPORT_OPERATION_MODE)

```

**Comment by wwolkers** [comment]
just created a pull request for this.

**Comment by gerritjonker** [comment]
Did you use the new custom component structure? Including `__init__.py` in every sensor directory?
I also had these errors because HA was using the standard Toon component. The `__init__.py` is used to tell HA to use the custom component.

**Comment by lxz81** [comment]
Yes, that was part of the problem. But pull request #21 fixed the imports. Now it is working again

**Comment by zuidwijk** [comment]
Whats exactly in the __init__.py ? I can't find it yet...

**edit: nevermind!**

I guess I had to remove the __pychache__ folder ;-)

**Comment by lxz81** [comment]
An empty file called __init__.py is all there is. See Ron's commit 77b1cb9 (Mar 07, 2019)

**Comment by zuidwijk** [comment]
> An empty file called `**init**.py` is all there is. See Ron's commit [77b1cb9](https://github.com/cyberjunky/home-assistant-custom-components/commit/77b1cb9bda8714fe1e7ff6b83a25dbe2f360c0f4) (Mar 07, 2019)

I've placed an empty __init__.py file and removed the __pycache__ folder and that worked! Great job/fix again!
