### ISSUE TITLE
Branderinfo Toon

### ISSUE THREAD

**Issue by Dennisd80** [cyberjunky/home-assistant-custom-components#26]
Hi, i'm searching for a way too include  the burnerInfo state of my rooted toon. I saw in your toon_google that you already pull the data, but not sure how it is displayed so i can use it.

**Comment by cyberjunky** [comment]
It's exposed with an attribute of the climate.toon. you can create a sensor with a template like this:
```  - platform: template
    sensors:
      toon_driewegklep:
        friendly_name: 'Driewegklep'
        value_template: >-
          {% if is_state_attr('climate.toon','burner_info', 0) %}
             Neutraal
          {% elif is_state_attr('climate.toon','burner_info', 1) %}
             CV
          {% elif is_state_attr('climate.toon','burner_info', 2) %}
             Warm Water
          {% endif %}

And then display it as a badge, sensor, or in lovelace custom thermostat as a sensor.

**Comment by Dennisd80** [comment]
Thanks, sorry  for being a noob ;) But i have copied the exact code in my configuration file and i do get a sensor with driewegklep, but unfortunately without any output of number or word.

**Comment by cyberjunky** [comment]
Check on your dev-state page how your toon device is called (mine is climate.toon) and replace the name in the template sensor. Also see if you have the burner-info attrib with numeric value on that page.
![image](https://user-images.githubusercontent.com/5447161/56151600-e5c12000-5fb1-11e9-8b68-8a5b45337d62.png)

**Comment by Dennisd80** [comment]
Succes, thanks
