### ISSUE TITLE
Toon with 0.92

### ISSUE THREAD

**Issue by NielsZeilemaker** [cyberjunky/home-assistant-custom-components#27]
I ran into a problem with HA 0.92, overriding a build in component now requires a manifest.json.
My fix was to rename the toon folder to toon_custom and use toon_custom instead of toon as the platform.

**Comment by Smiggel** [comment]
> I ran into a problem with HA 0.92, overriding a build in component now requires a manifest.json.
> My fix was to rename the toon folder to toon_custom and use toon_custom instead of toon as the platform.

Thank you! You just saved me a lot of time! After renaming it was fixed!

**Comment by joostvanmourik** [comment]
Thanx that saved a lot of time 👍

**Comment by zuidwijk** [comment]
Thanks! Saved me a lot of time too!

**Comment by cyberjunky** [comment]
I renamed it in the repo to toon_climate
