### ISSUE TITLE
Support for custom_updater

### ISSUE THREAD

**Issue by jeweet** [cyberjunky/home-assistant-custom-components#30]
Love the p2000 component.

Custom_updater support would be nice.

**Comment by TheRedBull205** [comment]
Custom_updater is end of life.
HACS is the new version: https://github.com/custom-components/hacs

https://custom-components.github.io/hacs/developer/general/

Not sure if you can have multiple custom components in 1 repo

**Comment by Tuncay-Ayhan** [comment]
Unfortunately thats not working for me. I've setup HACS but I can't find
the component anywhere in the ***"Store"***. Do you have an idea?

**Comment by TheRedBull205** [comment]
@Tuncay-Ayhan As described in the issue i don't think its possible with all plugins in 1 repositotry.

Final answer:
![HACS](https://user-images.githubusercontent.com/17354992/61552980-8c0d3d80-aa59-11e9-8ec2-4408e278cd61.PNG)

So for this issue to work, all plugins should be in a separate repos.

**Comment by Tuncay-Ayhan** [comment]
I was trying that, but the toon_climate component is also broken because
the new way HA interacts with the devices. So I'm stuck in there but I will
find a solution in the end.

Thanks for asking!

Regards,
Tuncay

**Comment by cyberjunky** [comment]
toon_climate is updated, please test, will look into HACS compatibility

**Comment by cyberjunky** [comment]
The components can now be found in HACS by default, just search for them.
