### ISSUE TITLE
Feature request: Total power usage current day

### ISSUE THREAD

**Issue by Smiggel** [cyberjunky/home-assistant-custom-components#32]
I Would like to see the feature added that calculates or displays the power usage of today. I would like to see how much power I used today. Now I always have to go to the Toon.

**Comment by wwolkers** [comment]
isn't that what the [Utility Meter](https://www.home-assistant.io/components/utility_meter/) component is for?

**Comment by Smiggel** [comment]
@wwolkers How do I make it work then? Do you have an example for me? Can't seem to figure it out.

**Comment by wwolkers** [comment]
this is what I have:

  daily_power_use_low:
    source: sensor.toon_p1_power_use_cnt_low
    cycle: daily
  daily_power_use_high:
    source: sensor.toon_p1_power_use_cnt_high
    cycle: daily
  daily_power_prod_low:
    source: sensor.toon_p1_power_prod_cnt_low
    cycle: daily
  daily_power_prod_high:
    source: sensor.toon_p1_power_prod_cnt_high
    cycle: daily
  daily_gas:
    source:  sensor.toon_gas_used_cnt
    cycle: daily
  weekly_power_use_low:
    source: sensor.toon_p1_power_use_cnt_low
    cycle: weekly
  weekly_power_use_high:
    source: sensor.toon_p1_power_use_cnt_high
    cycle: weekly
  weekly_power_prod_low:
    source: sensor.toon_p1_power_prod_cnt_low
    cycle: weekly
  weekly_power_prod_high:
    source: sensor.toon_p1_power_prod_cnt_high
    cycle: weekly
  weekly_gas:
    source:  sensor.toon_gas_used_cnt
    cycle: weekly
  monthly_power_low:
    source: sensor.toon_p1_power_use_cnt_low
    cycle: monthly
  monthly_power_high:
    source: sensor.toon_p1_power_use_cnt_high
    cycle: monthly
  monthly_power_low:
    source: sensor.toon_p1_power_prod_cnt_low
    cycle: monthly
  monthly_power_high:
    source: sensor.toon_p1_power_prod_cnt_high
    cycle: monthly
  monthly_gas:
    source:  sensor.toon_gas_used_cnt
    cycle: monthly

**Comment by Smiggel** [comment]
> this is what I have:
> 
> daily_power_use_low:
> source: sensor.toon_p1_power_use_cnt_low
> cycle: daily
> daily_power_use_high:
> source: sensor.toon_p1_power_use_cnt_high
> cycle: daily
> daily_power_prod_low:
> source: sensor.toon_p1_power_prod_cnt_low
> cycle: daily
> daily_power_prod_high:
> source: sensor.toon_p1_power_prod_cnt_high
> cycle: daily
> daily_gas:
> source: sensor.toon_gas_used_cnt
> cycle: daily
> weekly_power_use_low:
> source: sensor.toon_p1_power_use_cnt_low
> cycle: weekly
> weekly_power_use_high:
> source: sensor.toon_p1_power_use_cnt_high
> cycle: weekly
> weekly_power_prod_low:
> source: sensor.toon_p1_power_prod_cnt_low
> cycle: weekly
> weekly_power_prod_high:
> source: sensor.toon_p1_power_prod_cnt_high
> cycle: weekly
> weekly_gas:
> source: sensor.toon_gas_used_cnt
> cycle: weekly
> monthly_power_low:
> source: sensor.toon_p1_power_use_cnt_low
> cycle: monthly
> monthly_power_high:
> source: sensor.toon_p1_power_use_cnt_high
> cycle: monthly
> monthly_power_low:
> source: sensor.toon_p1_power_prod_cnt_low
> cycle: monthly
> monthly_power_high:
> source: sensor.toon_p1_power_prod_cnt_high
> cycle: monthly
> monthly_gas:
> source: sensor.toon_gas_used_cnt
> cycle: monthly

Aaaah! Thank you so much! I had no clue I could do it that way! You really helped me a lot with this!
