### ISSUE TITLE
p2000 cant get it to work on my hass

### ISSUE THREAD

**Issue by firefigther0575** [cyberjunky/home-assistant-custom-components#4]
getting the same error on hass every time did what was written...

Error fetching description at http://127.0.0.1:58080/dcf2819722.xml
18:27 ssdp.py (WARNING)
Error doing job: Task exception was never retrieved
18:27 loader.py (ERROR)

**Comment by cyberjunky** [comment]
SSDP has something to do with other auto-discovery of devices, P2000 component only fetches data from a portal, nothing on 127.0.0.1, did you find out what it was?
You can enable debugging for the component to get more output by adding this line to the logs: section of your config:

> custom_components.p2000: debug

You can should see loglines like these:

> 2018-01-27 10:35:00 DEBUG (Thread-12) [custom_components.p2000] Fetching data from feed "http://feeds.livep2000.nl?r=18&d=1,2,3,4"
> 2018-01-27 10:35:00 DEBUG (Thread-12) [custom_components.p2000] 50 entries available in feed "http://feeds.livep2000.nl?r=18&d=1,2,3,4"
> 2018-01-27 10:35:00 INFO (Thread-12) [custom_components.p2000] Restarted, last datestamp 2018-01-27 10:16:11.
> 2

**Comment by firefigther0575** [comment]
the poblems above had nothing to do with it.
after some searching still cant get is to work.
No module named 'gpxpy' and 
 General Errors: 
    - Component not found: p2000
    - Setup failed for p2000: Component not found.

try to add a simpel hello_state but that doesnt work either

**Comment by cyberjunky** [comment]
You have to follow the installation instructions here:
https://github.com/cyberjunky/home-assistant-custom-components#installation-4

Depending on environment you have installed hass, you need to manually install gpxpy en feedparser once, using pip3 or pip

**Comment by firefigther0575** [comment]
so i did already:
pip3 install gpxpy
Requirement already satisfied: gpxpy in /usr/local/lib/python3.5/dist-packages
pip3 install feedparser
Requirement already satisfied: feedparser in /usr/local/lib/python3.5/dist-packages

do i need to install more before it works?

**Comment by cyberjunky** [comment]
You have restarted hass after that as well I guess?
If so it looks like you installed the dependencies it in a different place than where hass is looking, like hass is installed in an venv and the pip3 aren't
How did you install hass?

**Comment by firefigther0575** [comment]
restarted the crap out of it, 
the hass is installed directly on a pi. 
both raspberry pi's it doesnt work, one off those is a hassio update tot the lastest.
maybe a fresh install wil help.
will instal a new resinos-hassio for dev so i can test it maybe i did something wrong

**Comment by cyberjunky** [comment]
If you look in the location where the gpxpy module was installed, do you see more (lots) of hass related packages? Or just a few non related ones?

> /usr/local/lib/python3.5/dist-packages

Mine are installed in a virtual environment, so I can see gpxpy next to home-assistant pkg itself.
I don't know how hass.io does this.

> ~/venv/lib/python3.5/site-packages$ ls
> Jinja2-2.10-py3.5.egg
> MarkupSafe-1.0-py3.5-linux-x86_64.egg
> PyChromecast-1.0.3.dist-info
> PyYAML-3.12-py3.5-linux-x86_64.egg
> SQLAlchemy-1.2.1.dist-info
> TwitterAPI
> TwitterAPI-2.4.6.dist-info
> __pycache__
> aiohttp-2.3.7-py3.5-linux-x86_64.egg
> aiohttp_cors
> aiohttp_cors-0.6.0.dist-info
> astral-1.4-py3.5.egg
> async_timeout-2.0.0-py3.5.egg
> blockchain
> blockchain-1.4.0.dist-info
> certifi-2018.1.18-py3.5.egg
> chardet-3.0.4-py3.5.egg
> cpuinfo
> crcmod
> crcmod-1.7.dist-info
> distro-1.2.0.dist-info
> distro.py
> docopt-0.6.2.dist-info
> docopt.py
> easy-install.pth
> easy_install.py
> eiscp
> enum_compat-0.0.2.dist-info
> feedparser-5.2.1.dist-info
> feedparser.py
> fritzconnection
> fritzconnection-0.6.5.dist-info
> future
> future-0.16.0.dist-info
> fuzzywuzzy
> fuzzywuzzy-0.16.0.dist-info
> gTTS_token-1.1.1.dist-info
> google
> googlemaps
> googlemaps-2.5.1.dist-info
> gpxpy
> gpxpy-1.1.2.dist-info
> gtts_token
> ha_ffmpeg-1.9.dist-info
> haffmpeg
> hass_frontend
> hass_frontend_es5
> home_assistant_frontend-20180126.0.dist-info
> homeassistant-0.62.0.dev0-py3.5.egg

...

**Comment by firefigther0575** [comment]
hassio is still installing.

same here on my running homeassistant

aiohttp_jinja2-0.14.0.dist-info
aiohttp-2.3.2.dist-info
appdaemon
appdaemon-2.1.11.dist-info
astral-1.4.dist-info
async
async_timeout
async_timeout-2.0.0.dist-info
async-0.6.2.dist-info
backports
bcrypt
bcrypt-3.1.4.dist-info
certifi
certifi-2017.11.5.dist-info
cffi
cffi-1.11.2.dist-info
chardet
chardet-3.0.4.dist-info
configparser-3.5.0.dist-info
daemonize-2.4.7.dist-info
feedparser-5.2.1.dist-info
gpxpy
gpxpy-1.1.2.dist-info
homeassistant
homeassistant-0.58.0.dist-info

**Comment by cyberjunky** [comment]
Whats inside the homeassistant directory?

**Comment by firefigther0575** [comment]
.vscode
__pycache__
components
helpers
scripts
util
.DS_Store
__init__.py
__main__.py
bootstrap.py
config.py
const.py
core.py
exceptions.py
loader.py
monkey_patch.py
package_constraints.txt
remote.py
setup.py

**Comment by cyberjunky** [comment]
Is version 0.58.0 also displayed in the GUI? Perhaps two hass instances are installed in different locations.

**Comment by firefigther0575** [comment]
this morning i did a update to 0.62.0
if so i need to reinstall everything. and thats a pain in the....

you where wright i found another hass

**Comment by cyberjunky** [comment]
Did you manage to clean it all up and get P2000 working?

**Comment by firefigther0575** [comment]
Due to time isseu and shift at the fire deparment today id did not have the time yet. Maybe tomorrow, keep you in the loop

**Comment by firefigther0575** [comment]
hey there,

clean hassbian instal all updated

  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/p2000.py", line 7, in <module>
    import gpxpy.geo
ImportError: No module named 'gpxpy'

**Comment by firefigther0575** [comment]
can you tell me what instal off home assistant you have?

**Comment by firefigther0575** [comment]
https://github.com/home-assistant/hassbian-scripts

**Comment by rjoosen** [comment]
same issue here......
Home Assistant 0.65.4, followed the instructions on the Github page

**Comment by cyberjunky** [comment]
I again tested with a clean install on a ubuntu machine after installing the two dependencies it works here without problems.

> 
(venv) ron@pc:~/.homeassistant$ pip3 install gpxpy
Collecting gpxpy
  Downloading gpxpy-1.2.0.tar.gz (96kB)
    100% |████████████████████████████████| 102kB 5.0MB/s
Building wheels for collected packages: gpxpy
  Running setup.py bdist_wheel for gpxpy ... done
  Stored in directory: /home/ron/.cache/pip/wheels/a2/f9/47/bf2a507f0ed5f8b6e85891113d650c7676e1619026103a436a
Successfully built gpxpy
Installing collected packages: gpxpy
Successfully installed gpxpy-1.2.0

(venv) ron@pc:~/.homeassistant$ pip3 install feedparser
Collecting feedparser
  Downloading feedparser-5.2.1.tar.bz2 (192kB)
    100% |████████████████████████████████| 194kB 3.7MB/s
Building wheels for collected packages: feedparser
  Running setup.py bdist_wheel for feedparser ... done
  Stored in directory: /home/ron/.cache/pip/wheels/4b/10/e1/ca5f42fc446e7844ee40a686a47a0d36f6088efe16f58fd97b
Successfully built feedparser
Installing collected packages: feedparser
Successfully installed feedparser-5.2.1

Can you guys show me how hass is started, so with a running hass type:

`ps -aux|grep hass`

I also see some older version of gpxpy installed above 1.1.2 instead of 1.2.0

**Comment by firefigther0575** [comment]
Error rendering data template: UndefinedError: 'trigger' is undefined

**Comment by cyberjunky** [comment]
Is this still an issue?
I added REQUIREMENTS = ['geopy','feedparser'] a few days ago to the code. It works on a recent hass.io I run, so no need to install stuff manually other than the p2000.py file itself.

**Comment by firefigther0575** [comment]
i got it more or less working.
notify works.
but can i show it in a panel?

**Comment by cyberjunky** [comment]
I'm working on a sensor instead of a platform. But don't know how to deal with multiple msgs af eachother they will overwrite previous ones. We need some kind of a logger card which show the last x values of a sensor...

**Comment by cyberjunky** [comment]
I have a beta version of a P2000 sensor working, so it shows the last event as state, and it even has the lat and long in its attributes so you can show it on a card.
Have to test is a bit more (notifies) and then I probably will replace the p2000 platform with a sensor.
![screenshot from 2019-01-29 10-18-05](https://user-images.githubusercontent.com/5447161/51897654-8a6a9300-23af-11e9-81bf-b407dea1da88.png)
![screenshot from 2019-01-29 10-18-45](https://user-images.githubusercontent.com/5447161/51897661-8c345680-23af-11e9-9225-739f2d89c43c.png)

What do you think?

**Comment by firefigther0575** [comment]
it looks very good, can you select the region? or a single capcode? so you can trigger lights @home when a pager goes off

**Comment by cyberjunky** [comment]
I replaced the p2000 component with the sensor version.
You can define multiple sensors with their own lat/lot, region, radius and discipline.
I like the fact that I can now click on the notify on my phone to zoom in on the location in google maps.
Please be careful not to stress the portal with too many queries.

**Comment by filmgarage** [comment]
Thanks! Your p2000 component is a great addition to my setup. I would like to add it to my automations now. What could be a good way to trigger events based on the text output of the sensor state. I would like to trigger home events for specific p2000 messages (based on fire truck codes etc.)
