### ISSUE TITLE
plugwise outlets not working  with home assistant 0.96

### ISSUE THREAD

**Issue by athebe** [cyberjunky/home-assistant-custom-components#41]
Hi, 
plugwise component isn't worrking anymore after updating to 0.96. 
can anyone put me in the right direction to get this fixed. 

thx, Athebe

**Comment by cyberjunky** [comment]
I had a more modern version locally but didn't submit it yet, I updated plugwise/switch.py and added manifest.json.
It works here under hass.io and version 0.98.1, can you copy both files, test and let me know?
If it doesn't please add 'custom_components.plugwise: debug' to your logger entry and capture debug output.

**Comment by athebe** [comment]
works like a charm, thx a lot.
