### ISSUE TITLE
Home Assistant Community Store support?

### ISSUE THREAD

**Issue by avenantsoftware** [cyberjunky/home-assistant-custom-components#45]
Could you perhaps configure this github repository to have support voor the Home Assistant Community Store, which makes it easy to update the custom components from within Home Assistant. https://hacs.xyz/

**Comment by cyberjunky** [comment]
Yes, I'm looking into that, but I guess I have to create new separate repos for them, will update on progress.

**Comment by avenantsoftware** [comment]
Cool thanx

**Comment by cyberjunky** [comment]
I have just create this https://github.com/cyberjunky/home-assistant-arpscan_tracker repo for arpscan_tracker component to test, it seems to work.
Which ones do you want to be ported first?

**Comment by cyberjunky** [comment]
These repositories are available to test with HACS:
https://github.com/cyberjunky/home-assistant-toon_smartmeter
https://github.com/cyberjunky/home-assistant-toon_climate
https://github.com/cyberjunky/home-assistant-plugwise
https://github.com/cyberjunky/home-assistant-arpscan_tracker
https://github.com/cyberjunky/home-assistant-hvcgroep
https://github.com/cyberjunky/home-assistant-p2000

**Comment by cyberjunky** [comment]
https://github.com/cyberjunky/home-assistant-toon_boilerstatus

**Comment by cyberjunky** [comment]
![hacs](https://user-images.githubusercontent.com/5447161/71031429-9f5d2b80-2113-11ea-9d99-bab84f9725ce.png)

**Comment by cyberjunky** [comment]
They are now added to HACS's default repo store, just search for them.
