### ISSUE TITLE
set_operation_mode programOn & programOff

### ISSUE THREAD

**Issue by RudolfRendier** [cyberjunky/home-assistant-custom-components#8]
I wanted to be able to tell Toon to resume it's normal program and I added the following to the toon.py climate-component.

```
        self._operation_list = ['Comfort', 'Home', 'Sleep', 'Away', 'Holiday', 'ProgramOn', 'ProgramOff']
```

```
    def set_operation_mode(self, operation_mode):
        """Set HVAC mode (comfort, home, sleep, away, holiday, programon, programoff)."""

        state = 2

        if operation_mode == "Comfort":
            mode = 0
        elif operation_mode == "Home":
            mode = 1
        elif operation_mode == "Sleep":
            mode = 2
        elif operation_mode == "Away":
            mode = 3
        elif operation_mode == "Holiday":
            mode = 4
        elif operation_mode == "ProgramOn":
            mode = -1
            state = 1
        elif operation_mode == "ProgramOff":
            mode = -1
            state = 0

        self._data = self.do_api_request(BASE_URL.format(
            self._host,
            self._port,
            '/happ_thermstat?action=changeSchemeState'
            '&state='+str(state)+'&temperatureState='+str(mode)))
        _LOGGER.debug("Set operation mode=%s(%s%s)", str(operation_mode),
                      str(state),str(mode))
```

ProgramOff disables Toon's program. ProgramOn re-enables it and activates the proper program according to Toon's schedule.

There's probably a more elegant way to solve this, but this works fine for me.

I could open a PR if that's helpful.

**Comment by joostvanmourik** [comment]
Thanx a lot for this, i use HomeAssistant to put Toon on Away if i leave home, but i like it to return to the programmed state when i'am ariving at home. This does the trick. Thanx

**Comment by RudolfRendier** [comment]
This code might interfere with Toon's schedule; it might skip programchanges shortly after a command from Home Assistant.
Looking for a proper fix.

**Comment by RudolfRendier** [comment]
~~It seems that setting state = 2 locks Toon to the manual program and ignores its schedule for some time. state = 1 in the snippet above will do.~~

state = 2 is required to change the setting

**Comment by cyberjunky** [comment]
Is this still an issue?
Shall I add an option in the config, to enable state 2 or 1 when switching modes?

**Comment by joostvanmourik** [comment]
Yes please 😀

Op wo 25 dec. 2019 15:16 schreef Ron Klinkien <notifications@github.com>:

**Comment by cyberjunky** [comment]
I have coded this, but it turns out to behave exactly like the current thermostat uit/verwarmen off/heating does.
I don't see what is different.

So in my code below you can switch off schedule with 'off' preset, and when pressing 'on' it resumes, or if you made manual changes to preset it jumps back to the pre-programmed schedule option, so if you manually put it on 'home' while thermostat was 'off' and you switch 'on', it jumps to 'away' if that was the schedule setting based on time.

You can find the code below, can you try it?
So it gives your preset mode 'on' and 'off', viewable in device params, or mini-thermostat gui.


[climate.py.txt](https://github.com/cyberjunky/home-assistant-toon_climate/files/4762909/climate.py.txt)

**Comment by joostvanmourik** [comment]
Will try to do this in the next couple of days. Let you know how it goes


Op do 11 jun. 2020 om 08:13 schreef Ron Klinkien <notifications@github.com>:

**Comment by RudolfRendier** [comment]
I don't think it's different from off/heating either, that works fine for me.
The request was created over 2 years ago, long before HA's climate system was refactored (and this component with it)

Closing makes sense to me, but since @joostvanmourik might still have a use case I'll leave it up to him.
