### ISSUE TITLE
Plugwise load depencency

### ISSUE THREAD

**Issue by pixiandreas** [cyberjunky/home-assistant-custom-components#9]
Hi 
I have a lot of plugwise and want to use them in hass.
But i have no idea how to use/place the dependency ?
> It has this dependency: python-plugwise

Can you explain a little bit more where to place them and which files ?

Thanks
Andreas

**Comment by Stephan296** [comment]
You have to follow this guide:
```
hg clone https://bitbucket.org/hadara/python-plugwise
cd python-plugwise
sudo python setup.py install
```

After that you have to place plugwise.py at your customcomponents directory inside your hass installation
